### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by misterdee0172** [LeL94/Crypto-Breakout-Bot#1]
First, very nice script!

It runs fine for a couple of coins when i receive a error.. see below:

AMP is consolidating: True is breaking out: False
ANC is consolidating: False is breaking out: False
ANKR is consolidating: True is breaking out: False
ANT is consolidating: True is breaking out: False
Traceback (most recent call last):
  File "C:\Users\user\Downloads\Crypto-Breakout-Bot-main\main.py", line 48, in <module>
    bot.start()
  File "C:\Users\user\Downloads\Crypto-Breakout-Bot-main\main.py", line 26, in start
    isConsolidating, isPumping = strategy.check_status_now(fsym)
  File "C:\Users\user\Downloads\Crypto-Breakout-Bot-main\strategy.py", line 72, in check_status_now
    return check_status_between_timestamps(fsym, startTsMs, nowTsMs, debug)
  File "C:\Users\user\Downloads\Crypto-Breakout-Bot-main\strategy.py", line 38, in check_status_between_timestamps
    df = util.get_symbol_data(fsym, startTsMs, endTsMs)
  File "C:\Users\user\Downloads\Crypto-Breakout-Bot-main\util.py", line 50, in get_symbol_data
    res = np.delete(res, obj=[6, 7, 8, 9, 10, 11], axis=1) # remove useless columns
  File "<__array_function__ internals>", line 180, in delete
  File "C:\Python310\lib\site-packages\numpy\lib\function_base.py", line 5040, in delete
    axis = normalize_axis_index(axis, ndim)
numpy.AxisError: axis 1 is out of bounds for array of dimension 1

Can you see whats going wrong? or is there mayb a update? :)

Like to hear from you
Dennis

**Comment by cyberjunky** [comment]
Problem is that queries for some symbol klines data return empy

See here for quick fix:
https://github.com/adrift942/Crypto-Breakout-Bot/pull/2

**Comment by misterdee0172** [comment]
> Problem is that queries for some symbol klines data return empy
> 
> See here for quick fix: #2

Thanks for the quick fix, works like a charm.

**Comment by quantoor** [comment]
@misterdee0172 thank you for reporting this bug, which has been solved by @cyberjunky. Closing the issue now.
